Implement native language translation during the non-lesson-plan chitchat dialog
eklavyamirani/DTML.EduBot pull request #49
Opened 2017-07-27 05:47 UTC by jsy1218

2017-07-27 05:53 UTC, eklavyamirani requested changes

2017-07-27 05:53 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/ChitChatDialog.cs
> +                context.Activity.AsMessageActivity().Text = await MessageTranslator.TranslateTextAsync(userInputText);
maybe a null reference.

2017-07-27 05:53 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/ChitChatDialog.cs
> +            return translatedBotResponse;
return raw response instead of empty string. Otherwise if userdata is null, all bot responses are blank.

2017-07-27 05:55 UTC, sinyaa requested changes

2017-07-27 05:55 UTC, seattleuser commented on DTML.EduBot/Dialogs/ChitChatDialog.cs
> +            string translatedBotResponse = string.Empty;
if userData is null bot will respond with empty text. It should be string translatedBotResponse = rawResponse

2017-07-27 05:55 UTC, seattleuser commented on DTML.EduBot/Dialogs/ChitChatDialog.cs
> +                translatedBotResponse = await MessageTranslator.TranslateTextAsync(rawResponse,
If translation fails we need to respond back in English

2017-07-27 05:55 UTC, seattleuser commented on DTML.EduBot/Dialogs/ChitChatDialog.cs
> +                // Suppress potential exception from await for demo purpose
The code above is quite fragile, we need to at least log the error to monitor

2017-07-27 06:15 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/ChitChatDialog.cs
> +                context.Activity.AsMessageActivity().Text = await MessageTranslator.TranslateTextAsync(userInputText);
context.Activity.AsMessageActivity().Text -> item.Text

2017-07-27 17:24 UTC, eklavyamirani requested changes
One small thing, check comment. Thanks!

2017-07-27 17:24 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/ChitChatDialog.cs
> +            if ((await item) != null && (await item).Text != null)
var activity = await item instead of "await item" multiple times. 

I am not very confident awaiting a task multiple times.

2017-07-27 18:47 UTC, eklavyamirani approved these changes

2017-08-16 00:54 UTC, eklavyamirani requested changes

2017-08-16 00:54 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/GreetingDialog.cs
>              await EngageWithUser(context);
Use Task.WhenAll on L#24 and L#23 to combine them into one task

2017-08-16 00:54 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/StartLessonPlanDialog.cs
> +                string translatedDeclineBotResponse = await this.TranslateBotResponseAsync(context, BotPersonality.BotResponseToDeclinedLessonPlan);
Why not translate the user response to english and compare with the english accept/decline?

2017-08-16 00:54 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/UserInformationDialog.cs
> +            await context.PostAsync(translatedBotResponse);
Can combine L#38 and L#39 into Task.WhenAll

2017-08-29 16:10 UTC, eklavyamirani commented
superseded by #62. Closing.

2017-08-29 16:10 UTC, closed without merging