Task - Implement multi-level dialog hierarchy for the lesson plan
eklavyamirani/DTML.EduBot pull request #5
Opened 2017-07-17 06:37 UTC by jsy1218

lesson plan construction at runtine without having to modify the source code. This is the intial check in for the prototype.

2017-07-18 01:47 UTC, eklavyamirani requested changes
Great job!

Looks good overall. Thank you for your hard work!

2017-07-18 01:47 UTC, eklavyamirani commented on DTML.EduBot/LessonPlan/Lesson.cs
> +
Do we also want to store progress here?

2017-07-18 01:47 UTC, eklavyamirani commented on DTML.EduBot/LessonPlan/LessonPlan.cs
> +        public ICollection<Lesson> Lessons
Progress here too?

2017-07-18 01:47 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/RootDialog.cs
> +                        await context.PostAsync("Congratz! You made it! Type anything if you would like to try another question.");
Let's move these conversational strings out into constants.

2017-07-18 01:47 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/RootDialog.cs
> +                    case "success":
Success, fail -> enums

2017-07-18 01:47 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/RootDialog.cs
> +                var selection = await result;
This looks great!

2017-07-18 01:47 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/RootDialog.cs
> +                lessonPlanDialog = WebApiApplication.FindContainer().Resolve<LessonPlanDialog>();
Why did we need a container to resolve the dependency for LessonPlanDialog here? Can you inject this dependency from constructor instead?

2017-07-18 01:47 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/LessonPlanDialog.cs
> +            foreach (Lesson lesson in LessonPlanModule.LessonPlan().Lessons)
Possible null reference. Lessons could be null. (Lesson plans Hard coded now, but it will be changed later)

2017-07-18 01:47 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/LessonDialog.cs
> +                if (value.Lesson.ToString().Equals(lesson.Topics.ToArray()[currentTopic].TopicName))
possible null reference exceptions?

2017-07-18 01:47 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/LessonDialog.cs
> +                        Text = "This is ________"
Can you move out this hard coded stuff and store it as data in this.lesson, so the text would look like -> 

Text = lesson.topic.questions[i].text (example)

Let's work with Soumya to build a lesson plan object for her lesson plans.

2017-07-18 01:47 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/LessonDialog.cs
> +    using System.Threading.Tasks;
can you either move the using statements inside or outside the namespace? currently they are mixed.

2017-07-18 01:47 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/GreetingDialog.cs
> +    public partial class RootQnaLuisDialog : QnaLuisDialog<object>
ChitChat dialog?

2017-07-18 01:47 UTC, eklavyamirani commented on DTML.EduBot/Controllers/MessagesController.cs
> +                    Activity reply = message.CreateReply("Hello, this is your EduBot!");
use the BotName constant instead of "Edubot"

2017-07-18 01:47 UTC, eklavyamirani commented on DTML.EduBot/Controllers/MessagesController.cs
> +                await HandleSystemMessage(activity);
Async methods would generally have an async suffix. Can you rename HandleSystemMessage to HandleSystemMessageAsync?

2017-07-18 04:35 UTC, jsy1218 commented on DTML.EduBot/Dialogs/RootDialog.cs
> +                lessonPlanDialog = WebApiApplication.FindContainer().Resolve<LessonPlanDialog>();
I wasn't aware of DI from ctor. Let me research on how to do it.

2017-07-18 04:35 UTC, jsy1218 commented on DTML.EduBot/LessonPlan/Lesson.cs
> +
I'm still thinking how to implement storing progress..

2017-07-19 17:59 UTC, jsy1218 commented on DTML.EduBot/Dialogs/RootDialog.cs
> +                lessonPlanDialog = WebApiApplication.FindContainer().Resolve<LessonPlanDialog>();
I decided not to declare lessonPlanDialog as a field, because it was used once in the class.

2017-07-19 18:41 UTC, jsy1218 commented on DTML.EduBot/Dialogs/GreetingDialog.cs
> +    public partial class RootQnaLuisDialog : QnaLuisDialog<object>
Modified.

2017-07-19 18:41 UTC, jsy1218 commented on DTML.EduBot/Dialogs/LessonDialog.cs
> +    using System.Threading.Tasks;
inside the namespace now.

2017-07-19 18:42 UTC, jsy1218 commented on DTML.EduBot/Dialogs/LessonDialog.cs
> +                        Text = "This is ________"
Yup, now it reads from the lesson plan file.

2017-07-19 18:44 UTC, jsy1218 commented on DTML.EduBot/Controllers/MessagesController.cs
> +                    Activity reply = message.CreateReply("Hello, this is your EduBot!");
Modified.

2017-07-19 18:44 UTC, jsy1218 commented on DTML.EduBot/Controllers/MessagesController.cs
> +                await HandleSystemMessage(activity);
Yup

2017-07-19 18:46 UTC, jsy1218 commented on DTML.EduBot/Dialogs/RootDialog.cs
> +                    case "success":
I actually changed the type from string to bool

2017-07-19 18:47 UTC, jsy1218 commented on DTML.EduBot/Dialogs/LessonDialog.cs
> +                if (value.Lesson.ToString().Equals(lesson.Topics.ToArray()[currentTopic].TopicName))
It shouldn't, because user has to type something to trigger the method delegate CheckAnswerAsync

2017-07-19 18:48 UTC, jsy1218 commented on DTML.EduBot/Dialogs/LessonPlanDialog.cs
> +            foreach (Lesson lesson in LessonPlanModule.LessonPlan().Lessons)
I'm thinking instead of null check, we should enforce the lesson to be present in the lesson plan.

2017-07-19 18:48 UTC, jsy1218 commented on DTML.EduBot/Dialogs/RootDialog.cs
> +                        await context.PostAsync("Congratz! You made it! Type anything if you would like to try another question.");
Do we want to do it now, or later, for addressing the style?

2017-07-20 02:43 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/RootDialog.cs
> +                lessonPlanDialog = WebApiApplication.FindContainer().Resolve<LessonPlanDialog>();
Well, it is still a dependency. This is kind of an [anti-pattern](http://blog.ploeh.dk/2010/02/03/ServiceLocatorisanAnti-Pattern/).

If it is not too much work, I'd suggest we move it out. Can you do it as a follow up later? I will not block the PR for this.

2017-07-20 02:44 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/LessonPlanDialog.cs
> +            foreach (Lesson lesson in LessonPlanModule.LessonPlan().Lessons)
either way, I would put it at both places honestly.

2017-07-20 02:50 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/LessonDialog.cs
> +                if (value.Lesson.ToString().Equals(lesson.Topics.ToArray()[currentTopic].TopicName))
okay.

2017-07-20 03:00 UTC, eklavyamirani requested changes
Remove LUIS and QNA keys before checking in.

Also follow up: use constructor injection instead of resolvers in code. We can talk about it if you want, and I can explain why. This [blog](http://blog.ploeh.dk/2010/02/03/ServiceLocatorisanAnti-Pattern/) explains it well.

2017-07-20 03:00 UTC, eklavyamirani commented on DTML.EduBot/Controllers/MessagesController.cs
> +                    await Conversation.SendAsync(activity, () => scope.Resolve<RootDialog>());
Followup: please use constructor injection.

2017-07-20 03:00 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/BasicDialogModule.cs
> +            builder.RegisterType<RootDialog>();
This is where the code would go for Constructor injection. You would need to replace the dependency injection in web api to use this resolver.

2017-07-20 03:00 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/ChitChatDialog.cs
> +    [LuisModel("31511772-4f1c-4590-87a8-0d6b8a7707a1", "a88bd2b022e34d5db56a73eb2bd33726")]
Remove keys before checking in please.

2017-07-20 03:00 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/RootDialog.cs
> +                        case ChatWithBot:
I might be missing something, but did you mention that you were using a bool now?

2017-07-20 03:00 UTC, eklavyamirani commented on DTML.EduBot/Dialogs/RootDialog.cs
> +                    case true:
If else? :) You can change it as a follow up if you want.

2017-07-21 02:48 UTC, eklavyamirani approved these changes

2017-07-21 02:49 UTC, merged

2017-07-21 03:09 UTC, eklavyamirani commented
@jsy1218 Please look at #7 and #8